"""Provenance-checked loading of agent.md from an authorized folder.

agent.md is descriptive documentation of a folder — it is generated by the
agent itself (see skills/init_doc.py: Purpose / Tech-stack / Layout /
Important files / Conventions / Avoid), not a policy file the agent must
obey. It is therefore injected as FENCED reference material, and only when
its location could not have been written by someone other than the owner.

Design: internal spec — AGENT.md trust model (2026-07-26)
"""
from __future__ import annotations

import errno
import os
import stat
from dataclasses import dataclass

FILENAME = "agent.md"
MAX_BYTES = 8 * 1024

# states
ABSENT = "absent"
LOADED = "loaded"
SKIPPED = "skipped"

# skip reasons
SYMLINK = "symlink"
NOT_REGULAR = "not_regular"
WRITABLE_FILE = "writable_file"
WRITABLE_PARENT = "writable_parent"
UNREADABLE = "unreadable"

# g+w or o+w — "somebody other than the owner can write here". We deliberately
# do NOT check st_uid: every NimoOS service runs as root, so anything written
# through NimoOS is root-owned, including whatever an attacker plants.
_WRITABLE_BITS = 0o022


@dataclass(frozen=True)
class AgentMdStatus:
    state: str
    reason: str | None = None
    detail: str | None = None
    body: str | None = None


def _ancestors(folder: str, ceiling: str | None):
    """Yield the folder itself, then each parent, up to and including the
    ceiling (or the filesystem root when ceiling is None).

    The folder itself is included on purpose: if it is writable, anyone can
    replace the agent.md inside it. Paths are realpath'd first so a symlinked
    ancestor cannot hide a writable directory behind a clean-looking path.
    """
    d = os.path.realpath(folder)
    stop = os.path.realpath(ceiling) if ceiling else None
    while True:
        yield d
        if stop is not None and d == stop:
            return
        parent = os.path.dirname(d)
        if parent == d:      # reached "/"
            return
        d = parent


def probe(folder: str, *, read_body: bool = True,
          max_bytes: int = MAX_BYTES,
          ceiling: str | None = None) -> AgentMdStatus:
    """Decide whether <folder>/agent.md may be injected, and read it if so.

    ceiling stops the ancestor walk (inclusive). Production passes nothing,
    so the walk reaches the filesystem root. Tests pass their tmp_path,
    because pytest's tmp_path lives under /tmp (mode 1777) which would
    otherwise make every fixture look world-writable.
    """
    path = os.path.join(folder, FILENAME)
    try:
        # O_NOFOLLOW: a symlink as the final component raises ELOOP.
        # O_NONBLOCK: a FIFO planted at this path would otherwise block this
        # open() forever (a one-line `mkfifo` DoS); with O_NONBLOCK the open
        # returns immediately and the S_ISREG check below fails it closed.
        # It is a no-op on regular files.
        fd = os.open(
            path,
            os.O_RDONLY | os.O_NOFOLLOW | os.O_CLOEXEC | os.O_NONBLOCK,
        )
    except (FileNotFoundError, NotADirectoryError):
        return AgentMdStatus(ABSENT)
    except OSError as e:
        if e.errno == errno.ELOOP:
            return AgentMdStatus(SKIPPED, SYMLINK, path)
        return AgentMdStatus(SKIPPED, UNREADABLE, path)

    try:
        # Check the OPENED file, not the path — the bytes we go on to read are
        # the bytes we checked, so nothing can be swapped in between.
        st = os.fstat(fd)
        if not stat.S_ISREG(st.st_mode):
            return AgentMdStatus(SKIPPED, NOT_REGULAR, path)
        if st.st_mode & _WRITABLE_BITS:
            return AgentMdStatus(SKIPPED, WRITABLE_FILE, path)

        for d in _ancestors(folder, ceiling):
            try:
                dmode = os.stat(d).st_mode
            except OSError:
                return AgentMdStatus(SKIPPED, UNREADABLE, d)
            if dmode & _WRITABLE_BITS:
                return AgentMdStatus(SKIPPED, WRITABLE_PARENT, d)

        if not read_body:
            return AgentMdStatus(LOADED)

        # Bounded read — never pull a whole file into memory. UTF-8 is at most
        # 4 bytes per character, so this cannot under-read the char budget.
        raw = os.read(fd, max_bytes * 4)
        body = raw.decode("utf-8", errors="replace")[:max_bytes]
        return AgentMdStatus(LOADED, body=body)
    except OSError:
        return AgentMdStatus(SKIPPED, UNREADABLE, path)
    finally:
        os.close(fd)
